import { useState } from "react";
import { Link, useNavigate } from "react-router-dom";
import { ArrowLeft, Lock, Mail, CheckCircle2, KeyRound } from "lucide-react";
import { changePassword } from "@/lib/api";
import { useToast } from "@/hooks/use-toast";

export default function ForgotPassword() {
    const [email, setEmail] = useState(""); const [currentPassword, setCurrentPassword] = useState("");
    const [password, setPassword] = useState(""); const [confirmPassword, setConfirmPassword] = useState("");
    const [loading, setLoading] = useState(false); const [success, setSuccess] = useState(false);
    const { toast } = useToast(); const navigate = useNavigate();
    const submit = async (event) => { event.preventDefault(); if (password.length < 8) return toast({ title: "New password must be at least 8 characters", variant: "destructive" }); if (password !== confirmPassword) return toast({ title: "New passwords do not match", variant: "destructive" }); setLoading(true); try { await changePassword({ email, current_password: currentPassword, password }); setSuccess(true); toast({ title: "Password changed successfully" }); setTimeout(() => navigate("/login"), 2200); } catch (err) { toast({ title: "Could not change password", description: err.message, variant: "destructive" }); } finally { setLoading(false); } };
    if (success) return <div className="min-h-screen flex items-center justify-center bg-background px-6"><div className="w-full max-w-md text-center space-y-5"><div className="mx-auto grid h-16 w-16 place-items-center rounded-full bg-emerald-100 text-emerald-600"><CheckCircle2 className="h-10 w-10" /></div><h2 className="text-2xl font-bold">Password Changed</h2><p className="text-sm text-muted-foreground">Your password has been updated. Redirecting to login…</p></div></div>;
    const field = (label, value, setValue, type = "password") => <label className="block text-sm font-medium">{label}<div className="relative mt-1.5"><Lock className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground" /><input className="h-11 w-full rounded-lg border bg-background pl-10 pr-4" type={type} required value={value} onChange={e => setValue(e.target.value)} /></div></label>;
    return <div className="min-h-screen flex items-center justify-center bg-background px-6 py-12"><div className="w-full max-w-md rounded-2xl border bg-card p-7 shadow-lg"><div className="mb-7"><div className="mb-4 grid h-11 w-11 place-items-center rounded-xl bg-primary/10 text-primary"><KeyRound className="h-5 w-5" /></div><h2 className="text-2xl font-bold text-foreground">Change Password</h2><p className="mt-1.5 text-sm text-muted-foreground">Enter your email and current password to set a new password.</p></div><form onSubmit={submit} className="space-y-4"><label className="block text-sm font-medium">Email address<div className="relative mt-1.5"><Mail className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground" /><input className="h-11 w-full rounded-lg border bg-background pl-10 pr-4 text-sm" type="email" required value={email} onChange={e => setEmail(e.target.value)} /></div></label>{field("Current Password", currentPassword, setCurrentPassword)}{field("New Password", password, setPassword)}{field("Confirm New Password", confirmPassword, setConfirmPassword)}<button disabled={loading} className="h-11 w-full rounded-lg bg-primary text-sm font-semibold text-primary-foreground disabled:opacity-60">{loading ? "Changing…" : "Change Password"}</button></form><div className="mt-7 text-center"><Link to="/login" className="inline-flex items-center gap-2 text-sm font-semibold text-primary hover:underline"><ArrowLeft className="h-4 w-4" />Back to login</Link></div></div></div>;
}
