import { useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { createPOApprovalLevel, deletePOApprovalLevel, fetchPOApprovalSettings, removePOApprovalLevelApprover, updatePOApprovalLevel } from "@/lib/api";

const empty = { name: "", min_amount: 0, max_amount: "", approver_ids: [], approval_rule: "any", is_enabled: true };
const inr = value => value === null || value === undefined ? "No upper limit" : `₹${Number(value).toLocaleString("en-IN")}`;

export default function POApprovalSettings() {
  const qc = useQueryClient(); const { data, isLoading } = useQuery({ queryKey: ["po-approval-settings"], queryFn: fetchPOApprovalSettings });
  const [form, setForm] = useState(empty); const [editingId, setEditingId] = useState(null);
  const refresh = () => qc.invalidateQueries({ queryKey: ["po-approval-settings"] });
  const add = useMutation({ mutationFn: ({ id, body }) => id ? updatePOApprovalLevel(id, body) : createPOApprovalLevel(body), onSuccess: () => { setForm(empty); setEditingId(null); refresh(); toast.success("Approval level saved."); }, onError: e => toast.error(e.message) });
  const remove = useMutation({ mutationFn: deletePOApprovalLevel, onSuccess: refresh, onError: e => toast.error(e.message) });
  const removeApprover = useMutation({ mutationFn: ({ levelId, userId }) => removePOApprovalLevelApprover(levelId, userId), onSuccess: () => { refresh(); toast.success("Approver removed from this level."); }, onError: e => toast.error(e.message) });
  if (isLoading) return <main className="p-8">Loading PO approval settings…</main>;
  // Present legacy duplicate records as one logical level. This matches the
  // workflow: many users are approvers of a level, not separate levels.
  const displayLevels = Object.values((data?.levels || []).reduce((all, level) => {
    const key = `${level.name}|${level.min_amount}|${level.max_amount ?? ""}|${level.approval_rule}`;
    if (!all[key]) all[key] = { ...level, ids: [level.id], approvers: [] };
    else all[key].ids.push(level.id);
    level.approvers.forEach(approver => { if (!all[key].approvers.some(item => item.id === approver.id)) all[key].approvers.push({ ...approver, levelId: level.id }); });
    return all;
  }, {}));
  const submit = e => { e.preventDefault(); add.mutate({ id: editingId, body: { ...form, min_amount: Number(form.min_amount), max_amount: form.max_amount === "" ? null : Number(form.max_amount) } }); };
  return <main className="mx-auto max-w-6xl space-y-8 p-5 sm:p-8"><div><h1 className="text-3xl font-extrabold">PO Approval Settings</h1><p className="mt-2 text-sm text-muted-foreground">Select the approvers directly for each amount range and level. These settings control who can approve new POs; submitted POs retain their audit trail.</p></div>
    <section className="rounded-xl border bg-white p-5 shadow-card"><h2 className="text-lg font-bold">{editingId ? "Edit approval level" : "Add approval level"}</h2><form onSubmit={submit} className="mt-4 grid gap-4 md:grid-cols-2"><label className="text-sm">Level name<input required value={form.name} onChange={e => setForm({...form,name:e.target.value})} className="mt-1 w-full rounded border p-2" placeholder="Level 1" /></label><label className="text-sm">Approval rule<select value={form.approval_rule} onChange={e => setForm({...form,approval_rule:e.target.value})} className="mt-1 w-full rounded border p-2"><option value="any">Any One approver</option><option value="all">All approvers</option></select></label><label className="text-sm">Minimum PO amount<input required type="number" min="0" value={form.min_amount} onChange={e => setForm({...form,min_amount:e.target.value})} className="mt-1 w-full rounded border p-2" /></label><label className="text-sm">Maximum PO amount <span className="text-muted-foreground">(blank = no limit)</span><input type="number" min="0" value={form.max_amount} onChange={e => setForm({...form,max_amount:e.target.value})} className="mt-1 w-full rounded border p-2" /></label><label className="text-sm md:col-span-2">Approvers<select multiple required value={form.approver_ids.map(String)} onChange={e => setForm({...form,approver_ids:[...e.target.selectedOptions].map(o => Number(o.value))})} className="mt-1 h-32 w-full rounded border p-2">{(data?.users || []).map(user => <option key={user.id} value={user.id}>{user.name} — {user.email}</option>)}</select><span className="text-xs text-muted-foreground">Use Ctrl/Cmd to select more than one user. Each assigned user also needs a PO approval permission below.</span></label><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={form.is_enabled} onChange={e => setForm({...form,is_enabled:e.target.checked})} /> Enabled</label><div className="flex justify-end gap-2">{editingId && <Button type="button" variant="outline" onClick={() => { setEditingId(null); setForm(empty); }}>Cancel edit</Button>}<Button disabled={add.isPending}>Save approval level</Button></div></form></section>
    <section className="rounded-xl border bg-white p-5 shadow-card"><h2 className="text-lg font-bold">Configured levels</h2><div className="mt-4 overflow-x-auto"><table className="w-full text-sm"><thead className="border-b bg-slate-50 text-left"><tr><th className="p-3">Range</th><th className="p-3">Level</th><th className="p-3">Approvers</th><th className="p-3">Rule</th><th className="p-3">Status</th><th /></tr></thead><tbody>{displayLevels.map(level => <tr key={level.ids.join("-")} className="border-b"><td className="p-3">{inr(level.min_amount)} – {inr(level.max_amount)}</td><td className="p-3 font-medium">{level.name}</td><td className="p-3"><div className="flex flex-wrap gap-2">{level.approvers.map(approver => <span key={approver.id} className="inline-flex items-center gap-1 rounded-full bg-slate-100 px-2 py-1 text-xs">{approver.name}<button type="button" title={`Remove ${approver.name}`} disabled={removeApprover.isPending} onClick={() => { if (window.confirm(`Remove ${approver.name} from ${level.name}?`)) removeApprover.mutate({ levelId:approver.levelId, userId:approver.id }); }} className="ml-1 font-bold text-destructive hover:text-red-800">×</button></span>)}</div></td><td className="p-3">{level.approval_rule === "all" ? "All" : "Any One"}</td><td className="p-3">{level.is_enabled ? "Enabled" : "Disabled"}</td><td className="p-3 text-right"><Button variant="ghost" onClick={() => { setEditingId(level.id); setForm({ name:level.name, min_amount:level.min_amount, max_amount:level.max_amount ?? "", approver_ids:level.approvers.map(a=>a.id), approval_rule:level.approval_rule, is_enabled:level.is_enabled }); window.scrollTo({ top:0, behavior:"smooth" }); }}>Edit</Button><Button variant="ghost" className="text-destructive" onClick={() => { if (window.confirm("Delete this approval level?")) remove.mutate(level.id); }}>Delete</Button></td></tr>)}{!displayLevels.length && <tr><td colSpan="6" className="p-6 text-center text-muted-foreground">No approval levels configured. POs remain automatically approved until a matching enabled level is added.</td></tr>}</tbody></table></div></section>
  </main>;
}
