import { useMemo } from "react";
import { useQuery } from "@tanstack/react-query";
import { useLocation, useNavigate } from "react-router-dom";
import { Bar, BarChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { AlertTriangle, Archive, ArrowDownToLine, ArrowLeftRight, ArrowUpFromLine, Bell, Box, Boxes, ClipboardCheck, ClipboardList, FileBarChart2, FileText, LayoutDashboard, Menu, PackageCheck, PackagePlus, ReceiptText, Search, Settings, ShieldCheck, ShoppingCart, Truck, Users, Warehouse } from "lucide-react";
import { fetchStoreDashboard, fetchStoreInventory, fetchStoreOrders } from "@/lib/api";
import { useAuth } from "@/context/AuthContext";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { cn } from "@/lib/utils";
import StoreModule from "./StoreModule";

const menu = [
    { label: "Inventory", icon: Boxes, slug: "items" },
    { label: "Material Requests", icon: ClipboardList, slug: "requests", count: 0 }, { label: "Purchase", icon: ShoppingCart, slug: "purchase", children: ["Quotations", "Purchase Orders", "Goods Receipt", "Purchase History"] },
    { label: "Suppliers", icon: Truck, slug: "suppliers" }, { label: "Stock Operations", icon: ArrowLeftRight, slug: "operations" }, { label: "Reports", icon: FileBarChart2, slug: "reports" },
    { label: "Approvals", icon: ClipboardCheck, slug: "approvals", count: 0 }, { label: "Masters", icon: Archive, slug: "masters" }, { label: "Documents", icon: FileText, slug: "documents" }, { label: "Users & Permissions", icon: Users, slug: "users" }, { label: "Settings", icon: Settings, slug: "settings" },
];

const Stat = ({ icon: Icon, label, value, detail, accent = "bg-primary/10 text-primary" }) => <div className="rounded-xl border border-border/70 bg-card p-4 shadow-card transition-shadow hover:shadow-elegant"><div className="flex justify-between gap-3"><div><p className="text-[11px] font-medium uppercase tracking-wider text-muted-foreground">{label}</p><p className="mt-2 text-2xl font-bold tracking-tight text-foreground">{value}</p>{detail && <p className="mt-1 text-xs text-muted-foreground">{detail}</p>}</div><div className={`grid h-10 w-10 place-items-center rounded-xl ${accent}`}><Icon className="h-5 w-5" /></div></div></div>;

export default function StorePurchase() {
    const { user, applicationRole, selectApplication } = useAuth(); const navigate = useNavigate(); const location = useLocation();
    const { data: summary = {}, isLoading } = useQuery({ queryKey: ["store-dashboard"], queryFn: fetchStoreDashboard });
    const { data: inventory = [] } = useQuery({ queryKey: ["store-inventory"], queryFn: fetchStoreInventory });
    const { data: orders = [] } = useQuery({ queryKey: ["store-orders"], queryFn: fetchStoreOrders });
    const metrics = useMemo(() => {
        const quantity = inventory.reduce((sum, item) => sum + Number(item.quantity || 0), 0);
        const low = inventory.filter(item => Number(item.quantity || 0) <= Number(item.reorder_level || 0) && Number(item.quantity || 0) > 0).length;
        const out = inventory.filter(item => Number(item.quantity || 0) <= 0).length;
        return { quantity, low, out, reorder: low + out };
    }, [inventory]);
    const movement = [{ name: "Mon", in: 0, out: 0 }, { name: "Tue", in: 0, out: 0 }, { name: "Wed", in: 0, out: 0 }, { name: "Thu", in: 0, out: 0 }, { name: "Fri", in: 0, out: 0 }, { name: "Sat", in: 0, out: 0 }];
    const role = applicationRole("store_purchase");
    // Store opens directly into Purchase Orders; there is no Store dashboard.
    const requestedSlug = location.pathname.split("/")[2];
    const activeSlug = !requestedSlug || requestedSlug === "dashboard" ? "purchase" : requestedSlug;
    if (activeSlug !== "dashboard") return <StoreModule slug={activeSlug} inventory={inventory} orders={orders} admin={role === "admin"} />;
    return <div className="min-h-screen bg-background lg:flex">
        <aside className="hidden h-screen w-64 shrink-0 flex-col bg-sidebar text-sidebar-foreground lg:flex"><div className="border-b border-sidebar-border px-5 py-5"><div className="flex items-center gap-3"><div className="grid h-10 w-10 place-items-center rounded-xl bg-cyan-400/15 text-cyan-200"><Warehouse className="h-5 w-5" /></div><div><p className="font-bold text-white">Store Purchase</p><p className="text-[10px] tracking-wider text-sidebar-foreground/60">MANAGEMENT SYSTEM</p></div></div></div><nav className="flex-1 overflow-y-auto px-3 py-4 space-y-1">{menu.map(({ label, icon: Icon, slug, count, children }) => <div key={label}>{children ? <><button onClick={() => navigate(`/store-purchase/${slug}`)} className={cn("flex w-full items-center gap-3 rounded-lg px-3 py-2.5 text-left text-sm font-medium", activeSlug === slug ? "bg-sidebar-accent text-white" : "text-sidebar-foreground hover:bg-sidebar-accent")}><Icon className="h-4 w-4" />{label}</button><div className="ml-5 border-l border-sidebar-border pl-2">{children.map(child => <button key={child} onClick={() => navigate(`/store-purchase/${slug}`)} className="block w-full rounded-md px-3 py-1.5 text-left text-xs text-sidebar-foreground/65 hover:bg-sidebar-accent hover:text-white">{child}</button>)}</div></> : <button onClick={() => navigate(slug === "dashboard" ? "/store-purchase" : `/store-purchase/${slug}`)} className={cn("flex w-full items-center gap-3 rounded-lg px-3 py-2.5 text-left text-sm font-medium transition", activeSlug === slug ? "bg-sidebar-accent border-l-2 border-cyan-400 text-white" : "text-sidebar-foreground/80 hover:bg-sidebar-accent hover:text-white")}><Icon className="h-4 w-4" />{label}{count > 0 && <span className="ml-auto rounded-full bg-cyan-400/15 px-2 py-0.5 text-[10px] text-cyan-200">{count}</span>}</button>}</div>)}</nav><div className="border-t border-sidebar-border p-4"><button onClick={() => { selectApplication(null); navigate("/"); }} className="flex w-full items-center gap-3 rounded-lg bg-sidebar-accent/50 px-3 py-2.5 text-sm text-sidebar-foreground hover:bg-sidebar-accent"><ArrowLeftRight className="h-4 w-4" />Switch Software</button></div></aside>
            <div className="min-w-0 flex-1"><header className="sticky top-0 z-20 flex h-16 items-center gap-3 border-b bg-card/95 px-4 backdrop-blur sm:px-6"><Button variant="ghost" size="icon" className="lg:hidden"><Menu className="h-5 w-5" /></Button><div className="hidden sm:block"><p className="text-sm font-bold">Store Purchase Dashboard</p><p className="text-[10px] text-muted-foreground">Inventory, purchase & stock operations</p></div><div className="mx-auto max-w-sm flex-1"><div className="relative"><Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground" /><Input placeholder="Search item, PO, supplier..." className="h-9 bg-secondary/60 pl-9 text-xs" /></div></div><div className="flex items-center gap-3"><div className="hidden text-right sm:block"><p className="text-xs font-bold">{user?.name}</p><p className="text-[10px] text-muted-foreground">{role === "admin" ? "Store Admin" : "View Only"}</p></div><div className="grid h-9 w-9 place-items-center rounded-full bg-gradient-primary text-xs font-bold text-white">{(user?.name || "?").slice(0, 1).toUpperCase()}</div><Button variant="outline" size="icon" className="relative"><Bell className="h-4 w-4" /><span className="absolute right-1.5 top-1.5 h-1.5 w-1.5 rounded-full bg-destructive" /></Button></div></header>
            <main className="p-4 sm:p-6 lg:p-8"><div className="mb-7 flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm font-medium text-cyan-700">Store Operations</p><h1 className="mt-1 text-2xl font-bold tracking-tight">Decision Dashboard</h1><p className="mt-1 text-sm text-muted-foreground">Monitor stock health, purchasing and pending approvals at a glance.</p></div><div className="flex gap-2">{role === "admin" && <Button className="bg-primary"><PackagePlus className="mr-2 h-4 w-4" />New Material Request</Button>}<Button variant="outline"><FileBarChart2 className="mr-2 h-4 w-4" />Reports</Button></div></div>
                <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Stat icon={Boxes} label="Total Items" value={isLoading ? "—" : summary.item_count || 0} detail="Active item masters" /><Stat icon={PackageCheck} label="Total Stock Quantity" value={metrics.quantity.toLocaleString()} detail="Across all locations" accent="bg-cyan-50 text-cyan-700" /><Stat icon={ReceiptText} label="Total Stock Value" value="₹0" detail="Value updates after receipts" accent="bg-emerald-50 text-emerald-700" /><Stat icon={ShoppingCart} label="Current Month Purchase" value="₹0" detail={`${summary.purchase_order_count || 0} purchase orders`} accent="bg-violet-50 text-violet-700" /><Stat icon={ArrowDownToLine} label="Today's Stock In" value="0" detail="Goods received today" accent="bg-emerald-50 text-emerald-700" /><Stat icon={ArrowUpFromLine} label="Today's Stock Out" value="0" detail="Material issued today" accent="bg-amber-50 text-amber-700" /><Stat icon={AlertTriangle} label="Low Stock" value={metrics.low} detail="Below minimum level" accent="bg-amber-50 text-amber-700" /><Stat icon={AlertTriangle} label="Out of Stock" value={metrics.out} detail="Immediate action required" accent="bg-red-50 text-red-700" /></section>
                <section className="mt-6 grid gap-6 xl:grid-cols-5"><div className="rounded-xl border bg-card p-5 shadow-card xl:col-span-3"><div className="mb-5 flex items-start justify-between"><div><h2 className="font-bold">Stock Movement</h2><p className="text-xs text-muted-foreground">Stock in vs stock out — this week</p></div><span className="rounded-md bg-secondary px-2 py-1 text-[10px] font-medium">Current week</span></div><div className="h-64"><ResponsiveContainer width="100%" height="100%"><BarChart data={movement}><CartesianGrid vertical={false} strokeDasharray="3 3" /><XAxis dataKey="name" fontSize={11} tickLine={false} axisLine={false} /><YAxis fontSize={11} tickLine={false} axisLine={false} /><Tooltip /><Bar dataKey="in" name="Stock In" fill="#159957" radius={[4,4,0,0]} /><Bar dataKey="out" name="Stock Out" fill="#173a70" radius={[4,4,0,0]} /></BarChart></ResponsiveContainer></div></div><div className="rounded-xl border bg-card p-5 shadow-card xl:col-span-2"><h2 className="font-bold">Stock Alerts</h2><p className="mt-1 text-xs text-muted-foreground">Items needing attention</p><div className="mt-5 space-y-3"><div className="flex items-center justify-between rounded-lg bg-red-50 px-3 py-3"><span className="flex items-center gap-2 text-sm font-medium text-red-700"><span className="h-2.5 w-2.5 rounded-full bg-red-500" />Out of Stock</span><strong className="text-red-700">{metrics.out}</strong></div><div className="flex items-center justify-between rounded-lg bg-orange-50 px-3 py-3"><span className="flex items-center gap-2 text-sm font-medium text-orange-700"><span className="h-2.5 w-2.5 rounded-full bg-orange-500" />Reorder Required</span><strong className="text-orange-700">{metrics.reorder}</strong></div><div className="flex items-center justify-between rounded-lg bg-amber-50 px-3 py-3"><span className="flex items-center gap-2 text-sm font-medium text-amber-700"><span className="h-2.5 w-2.5 rounded-full bg-amber-500" />Low Stock</span><strong className="text-amber-700">{metrics.low}</strong></div></div></div></section>
                <section className="mt-6 grid gap-6 lg:grid-cols-2"><div className="rounded-xl border bg-card shadow-card"><div className="flex items-center justify-between border-b p-5"><div><h2 className="font-bold">Recent Purchase Orders</h2><p className="text-xs text-muted-foreground">Latest purchase activity</p></div><Button variant="ghost" className="h-8 text-xs text-primary">View all</Button></div>{orders.length ? <div className="divide-y">{orders.slice(0, 5).map(order => <div key={order.id} className="flex items-center justify-between p-4 text-sm"><div><p className="font-medium">{order.order_number}</p><p className="text-xs text-muted-foreground">{order.supplier} · {order.item_name}</p></div><span className="rounded-full bg-blue-50 px-2.5 py-1 text-[10px] font-bold text-blue-700">{order.status}</span></div>)}</div> : <div className="p-8 text-center text-sm text-muted-foreground">No purchase orders yet. PO form format will be added as provided by you.</div>}</div><div className="rounded-xl border bg-card shadow-card"><div className="border-b p-5"><h2 className="font-bold">Recent Activities</h2><p className="text-xs text-muted-foreground">Important Store Purchase actions</p></div><div className="p-5 text-sm text-muted-foreground"><div className="flex gap-3"><div className="mt-1 h-2 w-2 rounded-full bg-cyan-500" /><p>Activity history will appear here as material requests, receipts and stock issues are recorded.</p></div></div></div></section>
            </main></div></div>;
}
